import "./headers/menu/menu.js";
import "./headers/header/header.js";
import "./home/products/products.js";
import "./wishlist/wishlistcon/wishlist.js";
import "./cart/carts/carts.js";
import "./home/homebs/homebs.js";
import "./pageproduct/pagePro/pagepro.js";
import "./product/shopPage/shopPage.js";
import "./wishlist/wishlistcon/wishlist.js";
