import "./headers/menu/menu.js";
import "./headers/header/header.js";
import "./home/products/products.js";
import "./wishlist/wishlistcon/wishlist.js";
import "./cart/carts/carts.js";
import "./home/bestSeller/bestSeller.js";
import "./pageproduct/pageProduct/pageProduct.js";
import "./collections/contentCollections/contentCollections.js";
import "./wishlist/wishlistcon/wishlist.js";
